#----------------------------------------------------------------------
# This file was generated by Q:\py\pc\pc\_encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

_calendar_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAjBJ"
    "REFUOI2lk81LlFEUh5/3w1EbczTmA5qoyEgCiyQQW1U7aRNU61q1CdpWtIhZRJsWbfoPAsFI"
    "MwrbhJBlfiFRRBBWOoSfM0gjxjBz7z2nxauOgRvpwOHcw4Xfec4598J/mgfwZGT1nqh3XVQO"
    "iAhOwIrgnOBEsU62ucNZxTmZenD1WFcI4FRvXunam9xN5VzfzEmAEEBEkwDx/hugCs6CODAm"
    "OlcrYKpQMWAMf+4MY4zUbwk40Q1dhf0pEBu52g2RCpgK2Cp8XQTAWEdNwEltJAsFUIlIRCIS"
    "txmBTAaA6oYAAI9fL+p62Wjvu2VVVe17v6Sqqk8/RPmzsSgfHI9ioVTWa4+mdIvAOEFUCQPo"
    "H1shCHwGxlcIA3gxucLo8n1GBgUVoW46x/HsHqomIvA3W1AgDDwun0kT+nCpO02dDxe70vhe"
    "QHvbUXw/4MLpTLRaK/xDoAKhD6+mC0wWHzIxpKgq4cfb+L7H7FyewA94PrFMNuGjbBewgqpS"
    "F0BPZ4qxIThy6DA/83P0dKYIvLt0t7ciTpmZL7GvuZ54fVhrwUqkFvgebz4VAZjN5/HwGP5c"
    "xAiIKN8XSrQ0xUg2N2xtLgSw1kYz8OH8iSRhcItzHUnefilytiPJwHiBH/NrJOIxUokGRJTA"
    "p0ZgXNRCx8EmFlfLtGUamV1aJ9sa49uvEtkEJJpipFsaI9LAw0mEHT0kK6O53plTRiRurMNY"
    "h7OCcYJ1dse/8Hut/HLHi93aX804TpCtCEjKAAAAAElFTkSuQmCC")
get_calendar_Data = _calendar_.GetData
get_calendar_Image = _calendar_.GetImage
get_calendar_Bitmap = _calendar_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_day_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAc9J"
    "REFUOI2lk79rVEEQxz/v7pkUp4UQDYgYFVQQE6yCEAmCELBKwGtsrLSIILZWkkLs7PwPRCUQ"
    "UbATFBJOLBQbIQgHppGoRESUnLydnRmLfe9+4CEEB5ZddpfPfL8zu/CfkQHcX/t+yzy7am4H"
    "zQw1iGaoGmpOVOsbikZH1d7cuXx8OgdQ9+vN6T1jO8m8tNyeAsgBzHwMoPH4GriDRjAFkbQO"
    "BUiAQkCE7ZsvEbHRLkDNS67DgX1gMQ2PJaQAKSAGWP8MgESlB1DrlWRzC9ySErOkRKsZGB8H"
    "IPQDYgl4NHGbS2f3/9P7yutNzoU4qEDUMHfyerr09P0KrY1VrpxZ5MPXdV60n3P+2BwLk00K"
    "cX51hCAJUKssOJDXMwAWJpt0QgeAb9tb3J2/R2tjFYAiKkGMGK0HEDXcIK/9LbkTOozUR7rA"
    "Qqwsdz8gGu7OrtJC62PK9u7TWw7tneDGk0XmTlygugvQGM37imhps15LFmaOzDJzdLbsS8b8"
    "qYtkWTYAqDqXADHipZwHa19S19wRBVElqBEkeR+pV8kY7IK7M3V4Nye1evve/QvDQi3JTg8p"
    "2qulh+3TYtaQqEhUNBqiRtQ4FPDj5+9nQw92Gn8AGpcuIyGyvtMAAAAASUVORK5CYII=")
get_calendar_view_day_Data = _calendar_view_day_.GetData
get_calendar_view_day_Image = _calendar_view_day_.GetImage
get_calendar_view_day_Bitmap = _calendar_view_day_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_month_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAeRJ"
    "REFUOI2lkrtrVFEQh7899240bAgI2V1QsAlYrU0CRhujrQiiqcXev8BSG1sb/wIbiW9B1kYW"
    "FTFRyYIShKBgEXAfdwmuJix7zzkzFufuIyZNcGCYMxz45jcP+E/LAdx7u1VT5ayoRiKCF3Ai"
    "eC94UZyXMfd4p3iRndtXT0zFACq6uLQwbQ5S+eby9wJADOBVDUDh8XVQBe9APFgb3mkfbAp9"
    "C9ayc6OGtZ4RQDTjKhwtgrjg6jJIH2wfXApfGwBYNw7wMhrJzwRUghKRoMQPIlAuA5BmAADu"
    "vmzods/qwJbfNVVV9cH7lqqqPloJ+bPVEJNuT6/d+aRDBdYLosrDlTYGiCLDk9U2cQTPP7aZ"
    "nDBU6wn5vKG61mK2dJg0m4EZtKBAHOVYOlMiNnDldIm8gUunSgBcmCuGOB9acE5GAOsFFYgN"
    "vFhLyMdQrScYk6NaTwCG8emHVjbucYATVJV8BBfni7srzhXJm1F+eSEoKByKRwAngRaZHK8+"
    "d3ZVrH3pYIU9Sgabi0M/LszAwPmTM7xe73CuMsOb9Q6LlRn+tY3NLlF2t8MtqCqV41M0tnrM"
    "lif50dzm2JEJNja7ewAAkh1fOCQnv2/d/zadesE6j3Ue7wTrBefdvoBff3rNfT8Oan8BS8wz"
    "nTw4DIgAAAAASUVORK5CYII=")
get_calendar_view_month_Data = _calendar_view_month_.GetData
get_calendar_view_month_Image = _calendar_view_month_.GetImage
get_calendar_view_month_Bitmap = _calendar_view_month_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_week_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXRJ"
    "REFUOI2lkz1rVFEQhp/sLqZYBIuEgFinDNrkP9inTqo0AXsrSSFpY2GXygSEEK0CphEVwTTp"
    "bYKNoCsEQowfy70z806Ks5u7RViu+MIwpzjzzDvnA/5TMwB7H8+fKGfWlboniRC4RIQIJR6a"
    "iCA8idDJ1uricg8gMh+tLN+e+5fOm/unSwA9ACnnAPqvNyATwkEBZmVdV2A1VAZm/Hn8DjPN"
    "XgNCOeIm3J0HeYn0EaQCq8Br+DwAwDxoAKHmSL6fQao4kYqTGGdgYQGAegQA4PnRIH8PLTMz"
    "X7wfTM0Hx9/y7Ocw17ZPEqADYCGUSRtVlvz6a9RWHHTGI7Qrh8qD2oS7GoCFSE2tm3BQNiaT"
    "ABfZcgQbde7P9hqAq2X7CcD45noA7k4Cux9+0O2UrEx23g6wCJ69+UptwdNXX7jVLYXdDg3A"
    "oozw8MEdPMZvP6//wk0KFdvlIbk+bb48vW9S3zwwD8KFhfDwGwEXl8PD1nNP0xWHIy2+xFk6"
    "cAAAAABJRU5ErkJggg==")
get_calendar_view_week_Data = _calendar_view_week_.GetData
get_calendar_view_week_Image = _calendar_view_week_.GetImage
get_calendar_view_week_Bitmap = _calendar_view_week_.GetBitmap

#----------------------------------------------------------------------
_date_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhRJ"
    "REFUOI19kF9LG1EUxH83uzapMcYgQqWIpJEtoUVJxaf2UbAI+XA++zkEv0ApKQgSZTEmFsoq"
    "RQRREt3Eu+eePjTZpP7pwMDlcGbunIExTLVa3dzZ2fkRBMFXwAfMkP76+vqX3d3d79VqdXM4"
    "+ysC6IBeAf7eHm9rNaKDA1y9zsJw6QrI7u/zZnWV34eHPGxvswCsgBn9Qj6bxS8WERFmSiWs"
    "51FSBaCrSrZQQER4PTtLZiJ1+s75PidnZ4gIrXYbVyrRm5ujNzOD5HKctFqICCenp+Qm7wZM"
    "B1yxWKS5uEi712PF8yirkhFBrWWQJPy0ljNreeccn6zlXpUVyPiTCT7Oz/Mhn0cfHkisxVmL"
    "8zxeifB+aopABCNCttvlPknGKRqNhiZJ8iKttRrHscZxrKqqSZJoo9FQhiU+wWAwIAxDKpUK"
    "nU4HEeH29patrS10WOwImecMwjDk/PycQqHA2toa5XKZ6elpkiRJOTL6x2A0rNVqqGrK4+Nj"
    "KpUK1loGgwFxHKeaJyc8jnhzc4NzDmstl5eXOOdwzqV7z3YwaRaGIUEQICIsLy9jjCGKInzf"
    "B9AMoADOOTcprtfrqCobGxvk83mccxhjuLi4SI3SDrrdLnd3dz1VdcYYJul5HsYYRIQoilha"
    "WqLf72OtHZ/QarXwPG92GOtFjBKICEdHR2OD6+vrb81m8/N/1Y/Q7/d/AfwB7h4+GltqMzoA"
    "AAAASUVORK5CYII=")
get_date_Data = _date_.GetData
get_date_Image = _date_.GetImage
get_date_Bitmap = _date_.GetBitmap

#----------------------------------------------------------------------
_folder_image_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAArBJ"
    "REFUOI3Fk0loUwsUhr875Ca5N4k2WlOr4jzUCYeHolhBLVQQ1J0bJxA3rlTcSBURRNciiqIg"
    "giI8nrz3HN5TUcQBQV2oxTq1BjRtrkmamya3uc0dkutCjeJC3HngX51zfv7/DPC7Q/hZ8swa"
    "bXZQC2+MJcaOGjayqaHYn3HXHnu6QQD/a438Y9OphQTSQRoDMGr09JYTqzdtXyJWbXDLFLMf"
    "qv+Y6es3woqUyZbUzZeKS+sKDixEndPa2jlh3uIGNRoLBlU1pKlhSRJEZEUBQUGONREcPROv"
    "pHP/8Lon7Sf7FskATw6tTk6aPW+sGBoWQFLw/SqSUEPyhpBkBWwXKGOWDMJTVyDnXzJUcTN1"
    "C6GAYKphNQAung9VKYziFqEKuOW6Pdty0HWdeKGXsuV8I/iop3qmtMyYO5BYhjp9JVbFwzde"
    "4Fv5LygQsjNItks2nydkpLAsr6dOUGmc3+v+sYO8HePCA5MREZl4dBYjNJnGZoVxcQXr9hFC"
    "1W6MXBot/d7LGYN3AeRcLveXpmnr/31W5G16gGtvaij42E4VajUA4hGRP8d1ozBIOdWJofcY"
    "tkcXgJwu+quO/Z2Snn/02Noa586eBOGAwKGbeSr3nhMUfJLDmwhZH0AQwUxR6k3qBx9TApB1"
    "o3Q2VZF2/b97Mldem7wyqjRHRPYuiyBffoY/ZHNVnIAwCaCG6uWwnM8DBBCFwrv9mxYPtxrC"
    "AssTFfoLJv91FXm77Si5VzpcvEVkKIsoCoiiQEwcZNBys3WC9vb2soZ5/NJrm0f9ChMDA5Wl"
    "YmdW3jlnwDm9xevuPE90kev3mT5lxyEmV8gWnDwQqm9hqlbeF4v2T/M872EymTzX1tZmAhEg"
    "2tHRsaDv8TWarZdjxifUuc2NDS1dGef2Lz3TV5XfQQBqfD6xGsAn/ccqfmaAdtsAAAAASUVO"
    "RK5CYII=")
get_folder_image_Data = _folder_image_.GetData
get_folder_image_Image = _folder_image_.GetImage
get_folder_image_Bitmap = _folder_image_.GetBitmap

#----------------------------------------------------------------------
_image_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZ1J"
    "REFUOI2lkb1rVEEUxX/3znu+t6skafYFRUEQO22sFPwL0ln6UUQQFLu0YiXGLnbWIlZaWdr4"
    "V0ggZXBBzIosK4n79u3MXIu3eZvN1woeZmDuzL1nzrkX/hMCcO/Zx43g5X5/6PPd0TFZYTbM"
    "c1jIeftp4+5aAhCMBy8f3+gsF4WIJBhgQJz8YQZm+7ERfMXDF59XgZqgvxuyolPI09fvuXBp"
    "icxFgmWgi6hQbxWcCt+2vrK+9gQfVAASgL0RqCZcvXKZazdv49RhFkASEEFFEFFUldQpMU7t"
    "JPuHCGRZTt46V+s9BdaYPEQwrkrG5RBEMItEC8SoCGBmOAn46g9mUwkNgRn8HHznV2/AOHqi"
    "BX6PdqjCxXpUQJH1Ge4NwPR4gh87bdJuOb2wDmZlk9ynRbc7ay9h4sYM1J1BXXaqf5fmHKRo"
    "tMzp24moFYSIAL3tzbkFve1NsBVCPEBQN8l48+p5E52MO0A1q2ChpYPoy8XzbalHOCGcrEMQ"
    "vK/I0vopATibuw+P1r/cGnq7HuKRiiPIE2invJuf+Q/4C/jZpV3a164lAAAAAElFTkSuQmCC")
get_image_Data = _image_.GetData
get_image_Image = _image_.GetImage
get_image_Bitmap = _image_.GetBitmap

#----------------------------------------------------------------------
_sm_down_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAPklE"
    "QVQokWP8//8/AymAiSTVw0QDCzKHkZERlzp4YDJhFcWlGouTMPWgiVDD08hGYlqI3QaIOqxe"
    "YhwGaQkAe/shAwkbFWIAAAAASUVORK5CYII=")
get_sm_down_Data = _sm_down_.GetData
get_sm_down_Image = _sm_down_.GetImage
get_sm_down_Bitmap = _sm_down_.GetBitmap

#----------------------------------------------------------------------
_sm_up_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAOElE"
    "QVQokWP8//8/AymAiSTVA6uBkZGRBA0Q1Vj1YNGArA5TD8V+wDQSTYQJjxxWccbhHNNU0wAA"
    "6oYGNKXvU8QAAAAASUVORK5CYII=")
get_sm_up_Data = _sm_up_.GetData
get_sm_up_Image = _sm_up_.GetImage
get_sm_up_Bitmap = _sm_up_.GetBitmap

#----------------------------------------------------------------------
_tag_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAo1J"
    "REFUOI2tk89LlGEQxz/v7ru75ma6qIc02HwjpKAw3nOBskYEHToYQdRxAy8ds6BDFLH+CQlC"
    "QYHoKZAo1CTC6uCWFCVELphm/kjf9cf+et/3mafDIm5Kt+Y0M8/Md+b5zgz8T9FvsNVrRvxx"
    "tD9G17Y/95Jk7jl6Y5iR7DBWZU6gIjkpYWvSaL6eCLTcQimS22+iSFa13ibSdDEhLpOrQzvg"
    "5rbi+2SMfVGMfYcxzGp0uDFRGF6xfLAC0WN2wAwTjLYgAlqT2dNBqJ1RyX7uUStjoCFQ34Fv"
    "cFOELrP2BGihuPQeLfQ0XiL9Tx7yLxlxpy5o+dmrN56xVpq6rPXsXZ17d1YvDfBwd7zhvsIG"
    "CHeUUbPDxIIwEz15L4a/iqEN/GKOtU996aLQGb+CAzD7CBsPTC2kqLIS+RcZtOAoIS2KjBTm"
    "7WBAgfggGhEwhcG5R1iisMyqJvKFhVFTKwg1XyZccxzZmomJt5VAK4LhCLiLoH3Mqlrq227Y"
    "4uUJRuowI3XkV7+xPvEYUynwvz5ABKRc3dEKalqvJkIRE7TGy62z+OFJWgmOKCzxsTwX3BKY"
    "0fN0VpKSfUqsZDIT3H8YVVggGNqPpoASCLhcaukuc7BnjNvimgxWHzoXU26Oxcn+zNbvFcLR"
    "Rg7E2+2CT2p3fLDSWB4gFTl45lpNvIONzDhFZ64ntzz9KxBpsOuajuKWsK+0/Sz2jTGxp4Pl"
    "AbpC9fbNmngCVdxg88dbhxJD4jG0Pj8NWmiwThGJHky9uVMe/V8ASkF+Ie1sLXxkcz6NUvTG"
    "u3GOdDO6Nvc9venkWfr2heziL0cVdw7KqPzCbD+WQEorYp7P9dbu8s5P3qfLL5H0PEaBvtOp"
    "HSL/ANikQvL/Oa4mAAAAAElFTkSuQmCC")
get_tag_Data = _tag_.GetData
get_tag_Image = _tag_.GetImage
get_tag_Bitmap = _tag_.GetBitmap

#----------------------------------------------------------------------
_tags_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnVJ"
    "REFUOI2Nkl9ozWEYx7/f93eObTTjYAzZykimXe5YTsilZKPdYGsWx5UipU65Imm50a5WSpia"
    "P83ZrtyxrBWrIaKUOVnkWGZz2tn58/57XPhTOmo+9++nz/s8D/GL8f72KKkShIqBQUS8h2g7"
    "Y4weRdF2N5+8P4Z/oADgRX9HPGB4CB61rqh7fD7XUJjLNBid74GXWglCQyNXWuP/EnC8vz0a"
    "MDzkrb6OWO8tEg0g15FwFD+pIG++D3YeJ4IuYwqte84++KtEESrhnUtLrLePCrtBbCKlTMBy"
    "gap3DJorW25c9d6lxTFR8gWCMW91MhTCVgBVJJyAjiIOhBFIlahQvc2bJKBipTOgirDIARHW"
    "gMpCaCCwIIyIOAocidVG2wEqRkoE3guKKAIiFiJGfj6wXsQS8EI4CiwAiHWlW7DazCin2jzV"
    "JAkLJdaLOKXghLAUsY6SFittpmBmSgu0HhXhQeXMWwi+kjAkLEQsRZyAsyEGKS4KnXPapUoL"
    "csVuD9RkBo+e8C4YAzihhHMQlSU4EajgWSbZmVq7dXN5hXFNyVOxQ3/dAQAMX94fD8K8YLRL"
    "e22SzsoAAIh2bRUrlp6v3rJFVa6pgylkkRoewfyHL2taro1N/REAwKNLe6POIwEypoiIeIHW"
    "bi4chKvqdu5AZfV6UClkPr3DyzsPvYFee/ja2BSxAIOnd3VENtT0bYhGUb50OYrZOUy9fo6H"
    "A0/eb6td0hgsJLj7dPLVvo3LUvlv0wcWLQ7D5PPITn1GmcnDzuZ6Fiz4zb14U4fJu76V9auQ"
    "+TibNjnbeOT2s+n/FgDAvWPbI9/nC2fCZVUXu24+LgDAD7oITKWdR0P4AAAAAElFTkSuQmCC")
get_tags_Data = _tags_.GetData
get_tags_Image = _tags_.GetImage
get_tags_Bitmap = _tags_.GetBitmap

