#----------------------------------------------------------------------
# This file was generated by ./_encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

_calendar_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAjVJ"
    "REFUOI2lk81LlFEUh5/3w1EbczTmA5qoyEICiyQQW1U7aRPkNmjVJmhb0SIUatWiTX9CFEaa"
    "UdgmhDLzC4kigtDSIfycIZwybObee06LV51ZtAkvHM49m999zu/c46kqOzkhwIORtVuqXHYq"
    "+0QEJ2BFcE5wolgnVeFwVnEiU3cuHukIAUT1anfH7uT/vNzTN3t8m8CJJAHi/VdAFZwFcWBM"
    "dC+XwJShZMAYft8YxhhXWyWw5YPC3hSIjULtpkgJTAlsGT4vAWCsq3jgnGwKeLCYB5WIRCQi"
    "cVsZyGQAKG8KoKrcf7mk6xtGH46sqKpq39tlVVV9/C6qn4xF9eB4lPPFDb10b0pVNSIwThBV"
    "wgD6x1YJAp+B8VXCAJ5NrjK6cps3g4KKUDPdw9HsLsomIvC3WlAgDDy6T6UJfbjQmabGh/Md"
    "aXwvoLXlML4fcO5kJhqtlYoHxgkqEPrwYjrPZOEuE0OKqhK+v47ve8zN5wj8gKcTK2QTPkq1"
    "gBVUlZoAutpTjA3BoQMH+Zabp6s9ReDdpLO1GXHKzEKRPY21xGvDSgtWIrXA93j1oQDAXC6H"
    "h8fwxwJGQESZXSzS1BAj2Vi3PbkQwFobeeDD2WNJwuAaZ9qSvP5U4HRbkoHxPF8XfpKIx0gl"
    "6hBRAp8KgXFRC237G1j6sUFLpp655XWyzTG+fC+STUCiIUa6qT4iDTxEVKo+ko72Ppo5UXYS"
    "N9ZhrMNZwTjBOvvPXVj79ec5gLfTdf4LI0JajfzqrHAAAAAASUVORK5CYII=")
get_calendar_Data = _calendar_.GetData
get_calendar_Image = _calendar_.GetImage
get_calendar_Bitmap = _calendar_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_day_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAc9J"
    "REFUOI2lk7FrVEEQh79373kpTgshGhAxKgRBTLAKQiQIQsAqgaQRLLWIILZWoqClnX+CEoQE"
    "BTtBIXpiodgIQYiYRqISi0DI4dvZmbHY9y53GATJwLLLsnzz+83sZO7OXqIAePRm87Y719Tt"
    "qJmhBtEMVUPNiWo9S9HoqNn7+1dGxgsAc78xO35g8H8y33nyZayrQM0GAVpL18EdNIIpiKRz"
    "KEEClAIibN96hYgO9ADqOjgcOQQW0/JYQUqQEmKAle8ASNSdGqhaBchgfQPckhKzpETrHRga"
    "AiD0AmIFWBi+x+Xzh//pffHdOhdC7Fcgapg7RZ4ePfu0SHttmavn5vn8c4WXqy+4ODLFzOgc"
    "pThbHSFIAjRqCw4UeQbAzOgcndAB4Nf2Bg+mH9JeWwagjEoQI0bbAYgablA0/pbcCR2aebML"
    "LMWqcvcCouHu7KsstL+mbB+/feDYwWFuPp1n6tQl6rcArYGip4iWLvNGsjBxYpKJk5NVXzKm"
    "z8ySZVkfoO5cAsSIV3Iev/6RuuaOKIgqQY0gyXszr5PR3wV3Z+z4fk5r/fe9Owu7hZlbF6Dq"
    "b+8urJ4Nai2JikRFoyFqRI27Aja3fj8HyPY6zn8AAjw0JkQ2H+cAAAAASUVORK5CYII=")
get_calendar_view_day_Data = _calendar_view_day_.GetData
get_calendar_view_day_Image = _calendar_view_day_.GetImage
get_calendar_view_day_Bitmap = _calendar_view_day_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_month_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAedJ"
    "REFUOI2lk7trVFEQh7977t1o2CgI+wAFm2C3NglEbYy2IoimFez9Cyy1sLbxTxAkvgXZNLIo"
    "iolKFpQgBAWLgPtEspqw7p5zZizO3UdYG8nAMGeab37zOJGqsh9LAO692a6octarxCKCF3Ai"
    "eC94UZyXMfd4p3iR3dtXT8wkAKK6uLRwyPxP5ZvL37JDBV7EAGQfXwdV8A7Eg7Xh3e+B7UPP"
    "grXs3qhgrWcMMJiDwtE8iAuuLoX0wPbA9eFLDQDrxgFeUkAEP1qgEpSIBCV+EIFiEYB+CkBV"
    "ubtS052u1YEtv62rquqDdw1VVX20GvJnayG2Ol29duejqmpQYL0gqjxcbWKAODY8WWuSxPD8"
    "Q5PpKUO52iKTMZTXG8wWDtJPZ2AGLSiQxBFLZwokBq6cLpAxcGmhAMCFuXyI86EF52QEsF5Q"
    "gcTAi/UWmQTK1RbGRJSrLYBhfPq+kY57HOAEVSUTw8X5/N6Kc3kyZpRfPhUUZA8kI4CTQItN"
    "xMtP7T0VK5/bWGFCyWBzSejHhRkYOH8yx6uNNudKOV5vtFks5SaucHOrQ5ze7XALqkrp+Ay1"
    "n11mi9N8r+9w7MgUm1udCQCApMeXHpL+unX/6+G+F6zzWOfxTrBecN79E7D9+08dINrvd/4L"
    "mR0/lTvJg80AAAAASUVORK5CYII=")
get_calendar_view_month_Data = _calendar_view_month_.GetData
get_calendar_view_month_Image = _calendar_view_month_.GetImage
get_calendar_view_month_Bitmap = _calendar_view_month_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_week_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXdJ"
    "REFUOI2lkz1rVUEQhp/7gSkuQoqEgNjaimnyH1KnDVilEeytREHrWNhZGQJB1CqQNKKCaJPe"
    "Rm0EvUKahKjJOfPxpthzck8Rwg0ZWGaL3WfemX23J4mrxBBg89PBQ4m1UN7MTCLBM4lIIoVH"
    "dlYQLiJz7+nqraUhQEr3V5auz12m8qNX32+fKYjMOYDR23sgQThkgFnZ1xVYDZWBGf8evMcs"
    "ZjqAdg6CG/OQXpa8gVRgFXgNX8cAmMdkBhHZAHrwex+URUlmURJtBhYWAKgbAJJ4vjvW32OT"
    "JL38ML4wv/7yS/uHx7q7vidJ9AEskpzyOSsTR/+N2oqCftvCtG6oPKgtcc8JwCJRXnivo6Ac"
    "FF2AJ9M60prKo5nhBOA5ZfkOoH25IYC7I2Dj4x8G/ZJT4sW7MRbBs52f1BY8efODa4NycdBn"
    "ArAoLSwvzuLRel9nf+G8yCxTa4ykz4+3vt2pI0fmgXkQnlgkHn4u4ODoZBugd9XvfArdHjm7"
    "CqypngAAAABJRU5ErkJggg==")
get_calendar_view_week_Data = _calendar_view_week_.GetData
get_calendar_view_week_Image = _calendar_view_week_.GetImage
get_calendar_view_week_Bitmap = _calendar_view_week_.GetBitmap

#----------------------------------------------------------------------
_date_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAiNJ"
    "REFUOI19klFLG0EUhb/ZXZtojDGIUCkiaSQltCgRBKF9FCxCfpzP/g7BP1BKCoJEWYwmhRKl"
    "iA8qWVzX2Tu3DyZraq0HDgzDnI97ZgZVRVUBTL1e39zZ2flRq9W+AgFghg7W1ta+7O7ufq/X"
    "65uAGeWMqtIzRq+AYG+Pd40G/YMDXLPJPI+6AnL7+7xdWeH34SEP29vMA1VV4xljDEAhl6NQ"
    "KiEiTJfLTPo+Zc+j7HnkjSFfLCIiTM7MkB+CjTHGG67JBwEnvR4iQufsDFcuE83OEk1PI/k8"
    "J50OIsLJ6WkGYNSxC65UKtFeWOAsilj2fSqqeCKotSRpyk9r6VnLe+dYs5Y7VZbBC8Yn+DQ3"
    "x8dCAX14ILUWZy3O93kjwoeJCWoiGBFygwF3afo0RavV0jRN/2trrcZxrHEcq6pqmqbaarUU"
    "MAEvKEkSwjCkWq3S7XYREW5vb9na2ho9eSbvJUAYhpyfn1MsFlldXaVSqTA1NUWapplHoL8A"
    "o81Go8Hoo6gqx8fHVKtVrLUkSUIcx1nmnwrPR7y5ucE5h7WWy8tLnHM457JzL97BOCwMQ2q1"
    "GiLC0tISxhj6/T5BEKCq6ukQpapuPNxsNlFV1tfXKRQKOOcwxnBxcZGBsjsYDAZEURQBzhjD"
    "uH3fxxiDiNDv91lcXOT+/h5r7VOFTqeD7/szQfBqo2wCEeHo6IiNjY1HwPX19bd2u/351fQz"
    "JUnyC+APLTpNBzUxn4gAAAAASUVORK5CYII=")
get_date_Data = _date_.GetData
get_date_Image = _date_.GetImage
get_date_Bitmap = _date_.GetBitmap

#----------------------------------------------------------------------
_folder_image_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAsVJ"
    "REFUOI2lk09sFHUUxz+/mdnpzLDd0kW6LUJoUAFRMWlQKC4kSk30QrhxsdFET3Iq4YBabzWc"
    "jZHEaGJMMCYKhKACUQnREAnBiFRKkf457LKd7baz/6Y7O7Mzsz8PyHIw0QMveaeX98n3fV++"
    "QkrJw5TyUNuA9l/Dz/Z3P22Yxms9mfV9qUcGemvLi+Hktd8Pjl95IPtfgIlhkQDWAn1Du587"
    "/sroW8NKHEDYoF7KxW23cOHHQxvVYqlujX5T2S3uezAxLKxtw3smNz67s9dK9XQZpmVYlqGq"
    "QkHTdRA6WqqfroFtRHWby8cOXHv5eP55DeC3D16dP3T06Hph9CRQdaSMUUWMGjVRNR2CEGjg"
    "1suYT7yI5tyi6YeLnRMMXbimaSUgJJIQqyZ6WIMYCBud8wKvhW3bpCt3WfFaDwDFhfzs41u3"
    "bq9mslhbXsLzI2T5JtJz/ukKRrCIGoSUHAejnMfzwtkOIOgbuhvueBsnSPHlZZc1SY1091Os"
    "WaWxdp3OhrSOd/EYRjxDeWmBVXYucirezwCa4zgn9419cuDM9Sp3Fqp8/1cbHUnQiqHdBiCd"
    "VPh6www6KzTyk5Tt2XIYtacAtEJN7vvodE69UYx4Y0+aS0cymAnBxA8O/i836BKS+dX9GF4O"
    "hAJunnph3h6/IusAWrFc+zzvq2PnDz/Gt7ddpssx65IK72STaGf/QDYDvlMGEZsA2ljREl5w"
    "z0AAxfLt90d3rfZ6TcHejM9yxeXcVI07b37I0rQNX/1EsllCUQSKIkgpKzS8sNQBZLPZRpKV"
    "j0/dDri6rLNJr/kvqH+WEmPPVMNPX49mJk+Q2hnJgitptFqkNJ/FauAIIYzOF9J+bnywX9kc"
    "x/Gvc3NzX4yMjLhAEugef+/docLVcww0px8dzJjbB/p6n5wqti7eVyD+L85CCIV7qVUAAbSB"
    "WErZBvgbWNk9hWlt4bwAAAAASUVORK5CYII=")
get_folder_image_Data = _folder_image_.GetData
get_folder_image_Image = _folder_image_.GetImage
get_folder_image_Bitmap = _folder_image_.GetBitmap

#----------------------------------------------------------------------
_image_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZpJ"
    "REFUOI2lkzFrVEEUhb973zxnX5TEwheIKAhip5WNgr/AzsrCFBIIEbv0qUTTiHbWIlYi2Fv4"
    "KyRgGVwQs2LCSty8fe/NXIvdTHaTGMEcZooz3Hs4Z+6MmBmngQNYXHv/IrTyYHsQOrvDY6ri"
    "NC08zBa8/vD8/qoDCFEWn67cLOfLUkQcBljqE8zAbJ8boa1ZevLxITAS2N4NvrxQyuOXb7l4"
    "+Tw+iwTzoHOoMNoqZCp8/fKZZ6uPaIJIijAYgqrj2tUrXL91h0wzzAKIAxFUBBFFVckzJU5E"
    "cpMxve/QKc6N/J4ASyEPCTR1RVPtgQhmkWiBGBUBzIxMAm09wOzAQhIwgx/9b/zs9WliS7TA"
    "r+EWdbiEjGvm/Q57v/tgerzA960Z8m51cGAlZlUq3qGg252O5/btm4FmZ9DMn5g/yztMSiQv"
    "//sgHYDFiAC9zY1/NvQ2N8DuplE6YHxJxqv1tcT+jntAPe1gttB+bKu5hRkZjXAsOF6HILRt"
    "jc/FksBZr++W1z/dHjR2I8YjHUfgcygcbwDktN/5D9Pyq1YzzeJ/AAAAAElFTkSuQmCC")
get_image_Data = _image_.GetData
get_image_Image = _image_.GetImage
get_image_Bitmap = _image_.GetBitmap

#----------------------------------------------------------------------
_sm_down_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAPklE"
    "QVQokWP8//8/AymAiSTVw0QDCzKHkZERlzp4YDJhFcWlGouTMPWgiVDD08hGYlqI3QaIOqxe"
    "YhwGaQkAe/shAwkbFWIAAAAASUVORK5CYII=")
get_sm_down_Data = _sm_down_.GetData
get_sm_down_Image = _sm_down_.GetImage
get_sm_down_Bitmap = _sm_down_.GetBitmap

#----------------------------------------------------------------------
_sm_up_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAOElE"
    "QVQokWP8//8/AymAiSTVA6uBkZGRBA0Q1Vj1YNGArA5TD8V+wDQSTYQJjxxWccbhHNNU0wAA"
    "6oYGNKXvU8QAAAAASUVORK5CYII=")
get_sm_up_Data = _sm_up_.GetData
get_sm_up_Image = _sm_up_.GetImage
get_sm_up_Bitmap = _sm_up_.GetBitmap

#----------------------------------------------------------------------
_tag_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAqBJ"
    "REFUOI2lk89vVFUUxz935s1M60xDx0JEKtC+GI0SjOYlrvgRcDBsXLgYAguXDIkbl0XjhmBk"
    "Kn+BTYySuCkEFxqCTQsaiciiLxCJkBA6iVBooZRHy3RemffOOS4abJXGjTc5i3PPySfne+73"
    "OjPj/5zMysQuuEB/caPys7P0J1d9eh+PuFrrrLPmGTc6/4PzVwXYBVezgj/ueg9VMv0fo0Lt"
    "aU2VWsern5Df8H5FhfGHp5fh3t8ApWHZIq6zD+c9h+XWVeIfna+K70qvBRkvT7bYjwqo0nhm"
    "gsxOG9O5q4dl5hwYZHp2o8qAKlVvzVYwZfHeJUQ4vLZq4bJus39EPMJo+8p7pncGbf57Hj65"
    "st/szyO28Nu7dn+YL//d75LzBKqQf2eJ2jrryqpMFN84WiadxZkjXVwgujoUqrLnhQMWAdz6"
    "2gUq4KlSp8OvxCMOUyJVQlUaGk8G2YyApqCGLGk/OXnC+Sr4XnEDcXR3zDOFXO9+8l2vo82J"
    "sibNCiZk8wVoT4OleB1r6Hnzo0CTFtlCN16hm9bsDeZ+PYGnAvG1z1EFVUITIlXoeuWDSq7g"
    "gRnJwhzTl78NVYlU8CXBT9qQtMHr3Gt7Vhpj9rQrqzCRLfUh8V2yuRJGvPR8wr7+2tIOVnUi"
    "gAonO1/aW5b2AtPjXzWaD2bIF9fRtXlXkLSp/6eVZ4ZdvbB+R6W0cTvN25cQYfDBH98NzU/d"
    "4PmNWyj1vl27fMwNrAq4P+yquZ5goGtzBVmc5/Gti5EKpyTl1NzkdTBlrf8W+dKL9YufuuAZ"
    "K6tAayqMssVNZVl8jAiD/QctAsZ+P+7C7r5twaPJmzyanookwQdCALfyO9/+xvmq1FUoS8Kh"
    "lz+0BkD4maumCbU0YSxNGdr5xfIi/wIH6m+23W0H3AAAAABJRU5ErkJggg==")
get_tag_Data = _tag_.GetData
get_tag_Image = _tag_.GetImage
get_tag_Bitmap = _tag_.GetBitmap

#----------------------------------------------------------------------
_tags_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkZJ"
    "REFUOI2N0UtI1EEcwPHvzKotlopLvkM92AMNoUNt0mZ17lCWEIkbGClEl+oQQqciwksHuyRB"
    "hAplpKZ0tqik8KAS9IJMEIzNHlruirv/eXXZFWuNHPgxvxn4fWZ+M8I5B8Dk/XAQIdvBFxLC"
    "F3DWYpWa18obtZ7uqDvbP8YaQwJM9p1qFTJzCEeF9RKd3lK0xluK1ehEvNNZKoTIGHpxs6F1"
    "LUBM3GsOCpk5ZLV3V9Z39QI1QBlggBngbexR+Az4WlQ8cfTQpcd/3EQ6ZLs1JiLru3qAg8BW"
    "YAPgB6qAuk0Nvbet0REH7WktCGTIKTUIVAN5yZNToZJ7VTquBwUilA4IGTDa9gMlgE4WpeYU"
    "VGSV6UfIwN9AhrUOayyrityqwlSujTFIbdJ/QXvePNY1Jh9MJyMFpNYRZ2hUCTWfBhhPjTon"
    "jgEfgG+rWkhBC8C0zMq4bD09nQ4kVId1lCwONLcBY8AUEAViyXw8NnR6uqR6m9/vmT3D5/ef"
    "XA0I5xzPbhxplT55VSsTsZ4eNMr0W+vAuMbsQO6Vgh3bZU5xJSoeY/rpc35+/lp8/NbLuRUA"
    "YOT64SDQjpAhAQFnHcrT0QxfZl5l/T5yCrcgpOTX7EdePxixxiZKT9wZm1sB/jWGLxwI55eX"
    "9pQHg/hz80nEosy9meDJwKtPFUUba/8LAAyeC4XzSgt7ynbtxCH5MfWeL+9m5r1lVbEuAOBh"
    "296wWtY9m6sKWJxdiHieqm3qHv++bgCgr2V3IBbXF7OzxLWm7ok4wG8pqSv7xVr/FQAAAABJ"
    "RU5ErkJggg==")
get_tags_Data = _tags_.GetData
get_tags_Image = _tags_.GetImage
get_tags_Bitmap = _tags_.GetBitmap

