Document: pc
Title: Debian pc Manual
Author: <insert document author here>
Abstract: This manual describes what pc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pc/pc.sgml.gz

Format: postscript
Files: /usr/share/doc/pc/pc.ps.gz

Format: text
Files: /usr/share/doc/pc/pc.text.gz

Format: HTML
Index: /usr/share/doc/pc/html/index.html
Files: /usr/share/doc/pc/html/*.html


