#----------------------------------------------------------------------
# This file was generated by /home/k/jp/TOOLS/make_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

_calendar_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAI1SURBVDjLpZPNS5RRFIef98NR"
    "G3M05gOaqMhCAoskEFtVO2kT5DZo1SZoW9EiFGrVok1/QhRGmlHYJoQy8wuJIoLQ0iH8nCGc"
    "Mmzm3ntOi1edWbQJLxzOPZvffc7v3OOpKjs5IcCDkbVbqlx2KvtEBCdgRXBOcKJYJ1XhcFZx"
    "IlN3Lh7pCAFE9Wp3x+7k/7zc0zd7fJvAiSQB4v1XQBWcBXFgTHQvl8CUoWTAGH7fGMYYV1sl"
    "sOWDwt4UiI1C7aZICUwJbBk+LwFgrKt44JxsCniwmAeViEQkInFbGchkAChvCqCq3H+5pOsb"
    "Rh+OrKiqat/bZVVVffwuqp+MRfXgeJTzxQ29dG9KVTUiME4QVcIA+sdWCQKfgfFVwgCeTa4y"
    "unKbN4OCilAz3cPR7C7KJiLwt1pQIAw8uk+lCX240JmmxofzHWl8L6C15TC+H3DuZCYarZWK"
    "B8YJKhD68GI6z2ThLhNDiqoSvr+O73vMzecI/ICnEytkEz5KtYAVVJWaALraU4wNwaEDB/mW"
    "m6erPUXg3aSztRlxysxCkT2NtcRrw0oLViK1wPd49aEAwFwuh4fH8McCRkBEmV0s0tQQI9lY"
    "tz25EMBaG3ngw9ljScLgGmfakrz+VOB0W5KB8TxfF36SiMdIJeoQUQKfCoFxUQtt+xtY+rFB"
    "S6aeueV1ss0xvnwvkk1AoiFGuqk+Ig08RFSqPpKO9j6aOVF2EjfWYazDWcE4wTr7z11Y+/Xn"
    "OYC303X+CyNCWo09HetwAAAAAElFTkSuQmCC")
get_calendar_Data = _calendar_.GetData
get_calendar_Image = _calendar_.GetImage
get_calendar_Bitmap = _calendar_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_day_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAHOSURBVDjLpZOxa1RBEIe/d/e8"
    "FKeFEA2IGBWCICZYBSESBCFglUDSCJZaRBBbK1HQ0s4/QQlCgoKdoBA9sVBshCBETCNRiUUg"
    "5PDt7MxY7HuXdxgEycKwyzJ88/vN7Gbuzl5WDvDozeZtd66p21EzQw2iGaqGmhPVaqFodNTs"
    "/f0rI+M5gLnfmB0/MPg/le88+TLWU6BmgwDtpevgDhrBFETSORQgAQoBEbZvvUJEB2qAqg8O"
    "Rw6BxRQeS0gBUkAMsPIdAIm60wNVKwEZrG+AW1JilpRotQNDQwCEOiCWgIXhe1w+f/if3hff"
    "rXMhxH4Fooa5kzdT0rNPi3TWlrl6bp7PP1d4ufqCiyNTzIzOUYiz1RWCJECjsuBA3swAmBmd"
    "oxu6APza3uDB9EM6a8sAFFEJYsRoOwBRww3yxt+Su6FLq9nqAQuxst11QDTcnX2lhc7XVO3j"
    "tw8cOzjMzafzTJ26RJUL0B7Ia020dNlsJAsTJyaZODlZziVj+swsWZb1AarJJUCMeCnn8esf"
    "aWruiIKoEtQIkry3mlUx+qfg7owd389prd6+9/7CbsvMrfaQ/O3dhdWzQa0tUZGoaDREjahx"
    "V8Dm1u/nANlev/MfAjw0JrMu09AAAAAASUVORK5CYII=")
get_calendar_view_day_Data = _calendar_view_day_.GetData
get_calendar_view_day_Image = _calendar_view_day_.GetImage
get_calendar_view_day_Bitmap = _calendar_view_day_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_month_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAHlSURBVDjLpVPLShxBFD3T3WOU"
    "UUGYByhkI+50o6Bmo3ErAVG3Qvb5giyThets8gmC+DYQzEaGBMUnBhQRJAEXQuZJ8Mlodz28"
    "t6rbGY2b4IXqU1XcOvfc01UxrTWeEx5/ptbOssQzILVylVKQChCMkucagrA6JKTQtK+uJyc6"
    "Gg2B0npwvLfJ+Z/KH2Z+J+4VEJs5nFh4B3BLUhCrBILAzv1bmvvAbWD2rt9nCSRqCCIfCFtT"
    "dFjYoUVIwgQ0BJEc5UxmIGoJuGkTMeBPiQ4qq4R8MEpkhJSSyZhMPyQA/4XP33L6qhLoKGbW"
    "8wZnNwoG5zftennLYum8ot9+2uWpVRBQBTISc5tFsBmu62BxqwjPBb7sFNFQ52DlZwnxOOFe"
    "Ae3pevihB07UArvguTGMv0rDo92x/jQoHyO9aZM43J2y2GNbEEJVCVgBt80Hv+5RJdLFFR0n"
    "ZpAjwqXtQmh3LQGxcT9xkvymJ/WwIiEridajfVZB4oVXJeBbx+FSxdX98oOK2YMyAoV/lER/"
    "zrP9COsB0Q11JfH9sIzXnUn8IBwkfBzHp+dUrOYtGA+ohc6Xjcj9raA904CT/BXaWupM8lOh"
    "wssXXiR98XH6V7NPRHzDeEjyJTCPRzxJcHZ5kzdX77nP+Q6ZHT+VaotBJwAAAABJRU5ErkJg"
    "gg==")
get_calendar_view_month_Data = _calendar_view_month_.GetData
get_calendar_view_month_Image = _calendar_view_month_.GetImage
get_calendar_view_month_Bitmap = _calendar_view_month_.GetBitmap

#----------------------------------------------------------------------
_calendar_view_week_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAFySURBVDjLpZM9a1RhEIWf7C6m"
    "WASLSEBsbUWb/AdrW8HKRrC3EgWttbCzUgQRtRK0ERVEm/Q2aiPoBtJEosZ7Z+Yci3tvdosg"
    "KxkY5m3eZ77OrNjmMDYBePhu55rNpbJOSqIEKVElSiZLC15UmpI2b104tTEBkH3l/MbRtf/J"
    "fP3x59P7FZS0BjB9dhlsqAQVRHTvtoFooQmI4NfV10TU6gJgmIPhxHFQdu7sIQ1EA9nCxxkA"
    "kTWfQZV6wAp83warq0TqKqkhAuvrALQ9ANvcfTnzz72wbd9/M/tnfPLhm7d/7Pni7U3bZgQQ"
    "JbTkOpswu7+DNroKRkMLy6qhyaINkak5IEpYSwJC/bgXASmWVWT0maerkzkgpaUFNACGzU0A"
    "MhMDD95uMR51UTb3Xs2IKu68+Eobxc2nXzgy7j6ORwu3ENW1cO7sMbIG7Xv/Fg4yqZtaLyS/"
    "v/Ho05m2NI0sIotKESWy8kDAzu6f5wArhz3nv90eObvZ0Hw1AAAAAElFTkSuQmCC")
get_calendar_view_week_Data = _calendar_view_week_.GetData
get_calendar_view_week_Image = _calendar_view_week_.GetImage
get_calendar_view_week_Bitmap = _calendar_view_week_.GetBitmap

#----------------------------------------------------------------------
_catalog_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAEzgAABM4BZ7gfbwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAAUdEVYdEF1dGhvcgBKYWt1YiBTdGVpbmVy5vv3LwAAACF0RVh0U291cmNlAGh0dHA6Ly9q"
    "aW1tYWMubXVzaWNoYWxsLmN6aWbjXgAAAEl0RVh0Q29weXJpZ2h0AFB1YmxpYyBEb21haW4g"
    "aHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvcHVibGljZG9tYWluL1nD/soA"
    "AAKgSURBVDiNpVNLTxNhFD33m+lzgAKiFApUIIpY0ECiCymGGHSpKw0a94aVMSxcmujCpYku"
    "XPgHjIlxhQ+sjRERFtiAhAq0RKDQ4dEWptPSls58nwslIYEYE+725Jzce849JITAYUb+FxiN"
    "Rq/MDb8Zq5PVR7bSympGEEbFSS8Kmm5uRJbUkVf9uwI0G5l9L7jQJElKCC5Ws7msbjEDD+t8"
    "TctOo6EFLi8lMww/Yxq6fScgWSgNYEAGgOC3YEN8M345sBKgxopGVJdW47y7HPVVD7D20n1q"
    "zfcUSW0Hmgl4j9swE9PRQoUigKLk117L5Xa6n9Dj/vXMFOzmJs44XPAYz8HHt1EYzCE39h2W"
    "9kZUSOso4wn8iDE01SiGNjX0mD7da/N0XuqNWSwy/ZdrFgeeDTNcu9qbb+3wO2QukC5mUkVZ"
    "yltJsiHHrUi4zkHOraLGmN/HJ+UoFObAxK+MVdWDTgYgw8nCua5CmDuIbFkxkXDiy4py8Abc"
    "QLkTGJ9dZ7Xu2jus98mUMMlqghvIpWIYHI1ieXIIE2OfMaPm9vGFaaC5iuF6tzcvhFiQvo4M"
    "31gUnr7guociUgfIVY9UUYbzSA1Cq1aoCR1tlRlAcIAxEAEQgJRdCp++2HdXLilRBpwlZUxV"
    "VXwMBOA72wnTBFaW47DZGdJMQGQ38OdfCWRVAHgg7I4iAMiGYSIcnkYymcJ2NotoZB7zkTkI"
    "ztHc0gJfuX3vARA7GRB0CNsxEwAYN022C0uyjHB4Grdv3YS/6wIyug4hWff5IBe3oGu6k4hK"
    "5dTm5geb3dYuETEXy+fI4ykdfPuO3G43FIeNJxZmFkaZvLpXgNE2j6cnAwAKtNtGIiIAUldP"
    "T2tZSdkLu6IkFyOz/aFQKH5AmKb4S6TD1vk3YkYvOBMTF70AAAAASUVORK5CYII=")
get_catalog_Data = _catalog_.GetData
get_catalog_Image = _catalog_.GetImage
get_catalog_Bitmap = _catalog_.GetBitmap

#----------------------------------------------------------------------
_date_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIESURBVDjLlVJtaxpBEH7uvNSL"
    "50skFBqCiDVYpCWiIAjtx4Ih4I/zs78jkD9QioVAUBGNWigqRfpBxSO+3LnbmY13mNQWOvAw"
    "uzszz7zsQEoJBomWzWY/V6vVb5lM5oruBr/tYBQKhU+1Wu0r+/CbF6cOA02Tv9jr5gbn+TyG"
    "d3cQlQpe40nYFry9xZvLS/y8v8fm+lrZ0lJqukbCTlYwCCsWw3a7RTgex3EggLiuK5jkYkYi"
    "ynYcjcLcEXOsvjvDNAx0BgPl1O31IIjEPjmBHQ5ja5rodLvK1nl48Ang9dgHRIyyN87O0LNt"
    "XFD2FLWmU4B0HKxdF99JDwhvhUCB9CPZLwDd2K/gw+kp3lsW5GYDl5wEg8heEdG7oyNkSGuE"
    "4GKBRyL1q6jX69J13b/CcRy5XC4VWPiNYzjWwAFZr9dot9tIp9Po9/uq9/l8jnK57H25L/oh"
    "Ag4ejUaI0ORzuRxSqRRCoRAosw+P6BmB95inXfAWhdFqtVQ1Dg+UqqNW/Jg/WnhZ4mw2g6DJ"
    "c/BkMlFnhud3cAb7ZNwOrbaaQzKZ5OXBcDiEQb/GA9XljoqU2A+u0CqzqVgswqKv5awcPB6P"
    "fSJ/Bgv6V5uEjoIN+wjQHrDmCjhzIpHAarVSLfktdGlNyTHKZf1LvAqYrNlsolQqPRFMp9Mv"
    "jUbjI/5D6Dd+sP4NLTpNB1cxufkAAAAASUVORK5CYII=")
get_date_Data = _date_.GetData
get_date_Image = _date_.GetImage
get_date_Bitmap = _date_.GetBitmap

#----------------------------------------------------------------------
_icon_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAmcAAAJnAHHfHvWAAAACXZwQWcAAAAQAAAAEABcxq3DAAACs0lEQVQ4y6VTS0tU"
    "YQA93/3uvMeZcRxtdNRRCCk0UyRJxhYWtBaix6JIXAdCm1Yh8wMCN0VrCYRctGhTSDrZItIU"
    "MmEadcSZfIzzcubO+977fV+rIjMi8GwPHA7nQYQQOA3kf5GJRGKw+n0tnJ57MiHZGzyAALM0"
    "yUQvc1Y4ULpGHwfJTwfhSPhNTa3t2Sy2iMfjOVJVtZzcf/FUVxq3HbK5j7paSbpiRCSuYOic"
    "A1Jitciq5TYihEAsHvOtbqzGZzdmJX+9H+3Odlxp86HNfAfJVw0oDU4jnGWgdiOMRg47MaFD"
    "XclTTfPJR9srcnVz+T7PJiSXFodUKKLJTGFOPkd5zwD2QUFxbgJtDx6CcgEjZ1jebYTPa2KU"
    "CpVE3z5rcWubcaNM6f+EJmQrphYpRq/3F7oDdQ6ZCyi6cliRZWYn1IgqN6Dk7AapZODWv58Q"
    "ILZGAE58y5ptvnyfXbJ1DpY0Tjkv7EOwGiIZCV+KrZjfd/3dAtdRZzHgUzglMZ3dkJu7BsTe"
    "ElHBdRTTu3i35gS3vMZuUkHfsAlnm8zHBZiKi+0yLrU0lBPJRIT6O/yB+fXU+PujTkOE9kO3"
    "elEWJjg8XqwcmhA/OEJvfQ4QAkSSARCAq5ByWzs91+49kl0u19UNQ501l8vj49Jn9A4MolSq"
    "IJNKw11vQ8pKIap5COQBQkAMNlD4IIRdAwCZMYZoNIpMJgtV07D+dR3ZVBK1moozzS3ovOD5"
    "rQIBoRYh8SyYbFFDoRCk0MIC+bVrakA8FsP42BgCQ5eh6zokiZzIUdIUlCo1MTIy4iBer/dm"
    "YHhoOp9XsBvfWbQ6GwN1VrPN29yMyFb00FE7CHW5efrYFgR4UtFXC87zL4kQAsFg0ATAAoC6"
    "6t090zMzE4zx0t3bt6ZKxUIEAP+zTADq5OQkJ6e98w9m+UmC2aQf2gAAABR0RVh0QXV0aG9y"
    "AEpha3ViIFN0ZWluZXLm+/cvAAAASXRFWHRDb3B5cmlnaHQAUHVibGljIERvbWFpbiBodHRw"
    "Oi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9wdWJsaWNkb21haW4vWcP+ygAAACV0"
    "RVh0ZGF0ZTpjcmVhdGUAMjAxMC0wMi0yNlQxNjozMjowOSswMTowMAS5CjwAAAAldEVYdGRh"
    "dGU6bW9kaWZ5ADIwMTAtMDItMjZUMTY6MzE6MjIrMDE6MDDe8VoEAAAAGXRFWHRTb2Z0d2Fy"
    "ZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAACF0RVh0U291cmNlAGh0dHA6Ly9qaW1tYWMubXVz"
    "aWNoYWxsLmN6aWbjXgAAAABJRU5ErkJggg==")
get_icon_Data = _icon_.GetData
get_icon_Image = _icon_.GetImage
get_icon_Bitmap = _icon_.GetBitmap

#----------------------------------------------------------------------
_icon_big_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAJnAAACZwBx3x71gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAAUdEVYdEF1dGhvcgBKYWt1YiBTdGVpbmVy5vv3LwAAACF0RVh0U291cmNlAGh0dHA6Ly9q"
    "aW1tYWMubXVzaWNoYWxsLmN6aWbjXgAAAEl0RVh0Q29weXJpZ2h0AFB1YmxpYyBEb21haW4g"
    "aHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvcHVibGljZG9tYWluL1nD/soA"
    "AAeQSURBVFiFxZdbbFzVFUDXuY+58/DM+Dm2Ez+S2AmJcZKmSUlaSEE0QKlaClVRhQC1qLRV"
    "JURbVapatR9VP/rTj6JWVZsiWhAfqF+oVEKEpnQIlIdN3gkmjkPs2ON4xsN47Jk7c5/n9MOO"
    "STAQg5DY0tHVvWefvdfdZ5/HFkopPk3RPlXvgPFJGTr8g7Xxsm71r0ZX6kHxlj9emAYQH3cK"
    "stlsa09vz9PTuenvOk9+O5/atO3ZlsEvbhNiMagChUJQj2TMWMeA4dXLypo96qBg7tyRqeLJ"
    "V2689c9jhRURGD46/LCUstOpO0c86R0r58sTd999t/deve6e7qcv5l6+YW3X3n9PfOa237b2"
    "X3ud0dxtKAGhErhmC7FUhqRucebcFJvWdSHlQoOlC5JOpXn29H9TwAoA0Znp/LUMZZMQglCG"
    "Pj3Y45PjFRSVwAtmbceeEoh+v3Zid2fqR5wfuadn/b6HfhfOnjJqoYmZXoMZS1Or1Dk0fJbx"
    "mSoL1TqbNnRRU3Ei0kaFYaibEQ/ekwPZbHZtX19f4olnniAf5ElbabM91d6YslKNLckWOls7"
    "SSaToGw0+Rt61pRJTf6V4edUcvPXfoYmJaffOk+llmPBNQiMJE0ZmPdNXj92hl2bO1D224SB"
    "Fxq+XAmgR/Sduq5HSqrECesEET1Ck2zC8i2ic1Fa5lt44LMP8M7EL9i9/SzeeeBMyMaXHuXE"
    "GKz/3kMcO1Pg+j070eYdBjdPs7FrOy8fPczQ0By7t/cRLkjCwJOh8P0VAFEruhOg4leWe4QQ"
    "CCHAgDu23EFx8u/sHDhIOA/u6cUmT4f0/OtRxlzFnQ//mMmZKtGIRVs6janFsSxJ7h2bIARP"
    "pBCBH0QTDe9G4ODPd6WTRvirSM+urxeijeyujbHVc9CFj1UJ0DWddcl1WK/9jUQky0xxDcFF"
    "FlsIQT/QD232a7iv7SdS8WiIJRgZrTFmeuSLGkm5hUNDp7lx13oqgScX6uFlUxA4Wzfsufmn"
    "DW29QinFpg1f/ZAFuGXx0fkhKu+RcINH6cVznJlI86UvDOILS7/9D2OXAUhtXoZhXc6eiiPD"
    "1VtepRiZrcSpMjlbx7ZdtK5djbC4AWkAgdIroe/Z0l1AKfmJAwihiOkeLkmee+kYqbUD8Ut9"
    "2qKCv+C7niuEjrILKwy8XW/hzbb7ONf9ICOZ+znvZj4SgAoD4paGYZq8NV7EjDdFsi9lty8D"
    "TNjRiuf5ShhRlFdF1t+5wsCk7CLR0kWssZOG1m4uyK6PFgLpEzN1DE3jQtEjX1oQzY3NP4Gl"
    "HPj+/jf8kf336BjWInF9Dhl6iEQ7QmgcevEFjp0rkGqIY9cdps4e58Y7Wz8CQEDM0jAMQagl"
    "ePbgMN/51r69yxEAkFLThG69GzbPRi5MoaTPMy+eQM0cQZsZJlY6yfP/O4kXrj5XVOhjmRod"
    "xgx3XdfI/d+8mSAI5MHsQWN5Iwrs4jiipePSe91XFEp1/vl6mZtu+QrFqEUlEkXXNfbckOIv"
    "L+T5xs5mupqt9/d6uYQu6bjgwbv2oFsWM8P/GLXbPzew76Z9oVBKMTg4GNnbqx3T2rdsSbe0"
    "kUw3YVoxXC/E832kCrGsKIZpoGkaYRBQLMyipI9Vn+G+QYfethgYUS4dx1dIpIEFOyBnrKct"
    "08HUoacOXP/L578MSzmw8ZqNEztuu7Wj5tQ4efwU0cZWSrMltm3dTq1e48zoCDMXZzCtKLoA"
    "M2ISsUzqtRDV1MfBkSEeiM4BIAwLjBjCjCPMpdUWemgqQPPmEVo7YeAFl9gMgOamxtZqzSaU"
    "Id3rejA1k2w2y3QuRyqdRppR1vQPMD87S3lujpnxHH0b1iI9H03XQVw234ELgYtyyqDpiEgS"
    "EU1jiAjCraGkQsnQuwKgXncZGhqic00n5bl5zp49C0IxlZukL9nIlv5+hl99Fdu20TUdyzCY"
    "mirQ2daEEIoPvFXJEOWUUU4ZYXWgPBMBCCmvBJBSIpUkN5WjWq0u/YpAaDpRK8p/DhxgYmKC"
    "UrFIPJGgu6cHx/UwdZ2eeOzqSQhoykH4dZSSSJSz/H3J2/sMUWi6wfETxxl5c4Q1mTYGNl+D"
    "79Qpzc7i+T52rUYymV4dQOigAgeQOL6UYilbNQCllFg5RBC34lSrNp5bZ8eOHTzyyCPce++9"
    "NCTiNMSiLFSqWFbk0rny4RI6iNBHKUWtHgigWQghNCGEUEq+jwWFG7gAmIbB6Ogo+Xye3t5e"
    "MpkMiUSCIAiYK5eQq7xZG9ImdGvUAymBKGAZgFWt2rK9I4Nt2wAkk0mS8biKGQFFTRNNzS2M"
    "jIzw2GOP0dbWRjQaIz99kUQiRv7cSbmpueK/OWVddWtUqkr5lWdqR0cLB4AQCAUQaW9vv31w"
    "67X7G9ONacdxyBcK5VMnT/3JcZzynhv2/tDx/IGGmEXMskimUrh+wGRumlKh8OTUhfFDQA7I"
    "X8W/XGoOUAXmlFL15cJECBEDEkAMiAA6QCKRiA7u2Pl43XF2mIZBEIYIIZQKgsePH3nj90AJ"
    "WFE3fABAsATgLvtdbWW0bffuzzdYsdtczyu6vvvcqcOHx1Y18CrysUuzT0o+9er4/xbLkyfI"
    "ccpMAAAAAElFTkSuQmCC")
get_icon_big_Data = _icon_big_.GetData
get_icon_big_Image = _icon_big_.GetImage
get_icon_big_Bitmap = _icon_big_.GetBitmap

#----------------------------------------------------------------------
_image_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAGWSURBVBgZpcE/a1NhGMbh3/Oe"
    "N56cKq2Dp6AoCOKmk4uCn8DNycEOIojilr2TaBfRzVnESQR3Bz+FFDoWA2IjtkRqmpyc97k9"
    "qYl/IQV7XSaJw4g0VlZfP0m13dwepPbuiH85fyhyWCx4/ubxjU6kkdxWHt69VC6XpZlFBAhw"
    "JgwJJHAmRKorbj94ewvoRBrbuykvT5R2/+lLTp05Tp45STmEJYJBMAjByILxYeM9jzr3GCcz"
    "GpHGYAQhRM6fO8uFy1fJQoaUwCKYEcwwC4QQaGUBd36KTDmQ523axTGQmEcIEBORKQfG1ZDx"
    "cA/MkBxXwj1ggCQyS9TVAMmZiUxJ8Ln/kS+9PmOvcSW+jrao0mmMH5bzHfa+9UGBmciUBJ+2"
    "Fmh1h+yTQCXSkJkdCrpd8btIwwEJQnaEkOXMk7XaiF8CUxL/JdKQOwb0Ntc5SG9zHXQNd/ZF"
    "GsaEeLa2ChjzXQcqZiKNxSL0vR4unVwwMENMCATib0ZdV+QtE41I42geXt1Ze3dlMNZFdw6U"
    "t6CIvKBhkjiM79Pyq1YUmtkKAAAAAElFTkSuQmCC")
get_image_Data = _image_.GetData
get_image_Image = _image_.GetImage
get_image_Bitmap = _image_.GetBitmap

#----------------------------------------------------------------------
_sm_down_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAAXNSR0IArs4c6QAAADBQTFRF"
    "AAAAgAAAAIAAgIAAAACAgACAAICAwMDAgICA/wAAAP8A//8AAAD//wD/AP//////TxMmSQAA"
    "AAFiS0dEAIgFHUgAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfYBg8MCRwpQ892AAAA"
    "JElEQVQI12P4DwUMJDIYgIAfxPgAZECkQAKojA8MMF38RJoMAIyob68oUdVdAAAAAElFTkSu"
    "QmCC")
get_sm_down_Data = _sm_down_.GetData
get_sm_down_Image = _sm_down_.GetImage
get_sm_down_Bitmap = _sm_down_.GetBitmap

#----------------------------------------------------------------------
_sm_up_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAAXNSR0IArs4c6QAAADBQTFRF"
    "AAAAgAAAAIAAgIAAAACAgACAAICAwMDAgICA/wAAAP8A//8AAAD//wD/AP//////TxMmSQAA"
    "AAFiS0dEAIgFHUgAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfYBg8MCSQBQXfoAAAA"
    "KUlEQVQI12P4DwUMBBj8UMYHBiiDgYEflfGBgYEBzADSQCEGYk1GYQAAWPpvr8q/K38AAAAA"
    "SUVORK5CYII=")
get_sm_up_Data = _sm_up_.GetData
get_sm_up_Image = _sm_up_.GetImage
get_sm_up_Bitmap = _sm_up_.GetBitmap

#----------------------------------------------------------------------
_tag_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9cLEg8wGmdXoIYAAAKg"
    "SURBVDjLpZPPb1RVFMc/d+bNTOtMQ8dCRCrQvhiNEozmJa74EXAwbFy4GAILlwyJG5dF44Zg"
    "ZCp/gU2MkrgpBBcagk0LGonIoi8QiZAQOolQaKGUR8t0Xpn3zjkuGmyVxo03OYtzz8kn53vu"
    "9zoz4/+czMrELrhAf3Gj8rOz9CdXfXofj7ha66yz5hk3Ov+D81cF2AVXs4I/7noPVTL9H6NC"
    "7WlNlVrHq5+Q3/B+RYXxh6eX4d7fAKVh2SKusw/nPYfl1lXiH52viu9KrwUZL0+22I8KqNJ4"
    "ZoLMThvTuauHZeYcGGR6dqPKgCpVb81WMGXx3iVEOLy2auGybrN/RDzCaPvKe6Z3Bm3+ex4+"
    "ubLf7M8jtvDbu3Z/mC//3e+S8wSqkH9nido668qqTBTfOFomncWZI11cILo6FKqy54UDFgHc"
    "+toFKuCpUqfDr8QjDlMiVUJVGhpPBtmMgKaghixpPzl5wvkq+F5xA3F0d8wzhVzvfvJdr6PN"
    "ibImzQomZPMFaE+DpXgda+h586NAkxbZQjdeoZvW7A3mfj2BpwLxtc9RBVVCEyJV6Hrlg0qu"
    "4IEZycIc05e/DVWJVPAlwU/akLTB69xre1YaY/a0K6swkS31IfFdsrkSRrz0fMK+/trSDlZ1"
    "IoAKJztf2luW9gLT4181mg9myBfX0bV5V5C0qf+nlWeGXb2wfkeltHE7zduXEGHwwR/fDc1P"
    "3eD5jVso9b5du3zMDawKuD/sqrmeYKBrcwVZnOfxrYuRCqck5dTc5HUwZa3/FvnSi/WLn7rg"
    "GSurQGsqjLLFTWVZfIwIg/0HLQLGfj/uwu6+bcGjyZs8mp6KJMEHQgC38jvf/sb5qtRVKEvC"
    "oZc/tAZA+Jmrpgm1NGEsTRna+cXyIv8CB+pvttOCYaEAAAAASUVORK5CYII=")
get_tag_Data = _tag_.GetData
get_tag_Image = _tag_.GetImage
get_tag_Bitmap = _tag_.GetBitmap

#----------------------------------------------------------------------
_tags_ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJGSURBVDjLjdJLSNRBHMDx78yq"
    "LZaKS75DPdgDDaFDbdJmde5QlhCJGxgpRJfqEEKnIsJLB7skQYQKZaSmdLaopPCgEvSCShCM"
    "zR5a7oq7/3l12RVtjfzBMA/4fWZ+MyOccwBM3g8HEbIdfCEhfAFnLVapOa28Uevpjrqz/WOs"
    "ERJgsu9Uq5CZQzgqrJfo9BajNd5irEYn4p3OUiFExtCLmw2tawFi4l5zUMjMIau9u7K+qxeo"
    "AcoAA0wDb2OPwmfA16LiiaOHLj1edRLpkO3WmIis7+oBDgJbgQ2AH6gC6jY19N62RkcctKeV"
    "IJAhp9QgUA3kJXdONZVcq9JxPSgQoXRAyIDRth8oAXQyKdWnoCKrTD9CBv4GMqx1WGNZkeRW"
    "JKbG2hiD1Cb9FbTnzWFdY/LCdLKlgNQ84gyNKqHm0gDjqVHnxDHgA/B9RQkpaB6YklkZl62n"
    "p9KBhOqwjpKFgeY2YAz4BESBWHI8Hhs6PVVSvc3v98ye4fP7T676B845nt040ip98qpWJmI9"
    "PWiU6bfWgXGN2YHcKwU7tsuc4kpUPMbU0+f8+vKt+Pitl7PLAMDI9cNBoB0hQwICzjqUp6MZ"
    "vsy8yvp95BRuQUjJ75mPvH4wYo1NlJ64Mza7DPwrhi8cCOeXl/aUB4P4c/NJxKLMvpngycCr"
    "zxVFG2v/CwAMnguF80oLe8p27cQh+fnpPV/fTc95S6piXQDAw7a9YbWkezZXFbAwMx/xPFXb"
    "1D3+Y90AQF/L7kAsri9mZ4lrTd0TcYA/Kakr+x2JSPUAAAAASUVORK5CYII=")
get_tags_Data = _tags_.GetData
get_tags_Image = _tags_.GetImage
get_tags_Bitmap = _tags_.GetBitmap

